### ISSUE TITLE
Error occur when infering. FileNotFoundError config.yaml

### ISSUE THREAD

**Issue by EduTecher** [openvpi/SOME#1]
(pyenv310) ➜  SOME git:(main) python infer.py --model /home/tong/Desktop/core/core/project/llm/rmvpe.pt --wav /home/tong/Desktop/temp/demo.mp3
Traceback (most recent call last):
  File "/home/tong/Desktop/core/core/project/llm/SOME/infer.py", line 47, in <module>
    infer()
  File "/home/tong/Desktop/core/core/project/llm/pyenv310/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/tong/Desktop/core/core/project/llm/pyenv310/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/tong/Desktop/core/core/project/llm/pyenv310/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tong/Desktop/core/core/project/llm/pyenv310/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/tong/Desktop/core/core/project/llm/SOME/infer.py", line 21, in infer
    with open(model_path.with_name('config.yaml'), 'r', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tong/Desktop/core/core/project/llm/config.yaml'

**Comment by yqzhishen** [comment]
--model accepts checkpoint path of SOME, not RMVPE

**Comment by EduTecher** [comment]
潼收到
