### ISSUE TITLE
一键整合包无法正常启动

### ISSUE THREAD

**Issue by NaughtDZ** [openvpi/SOME#11]
*     
I:\some>I:\some\run.bat
I:\some>python\python.exe webui.py --work_dir="dpcda"
Traceback (most recent call last):
  File "I:\some\webui.py", line 9, in <module>
    import librosa
  File "I:\some\python\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "I:\some\python\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "I:\some\python\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "I:\some\python\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "I:\some\python\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "I:\some\python\lib\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "I:\some\python\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "I:\some\python\lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.25 or less")
ImportError: Numba needs NumPy 1.25 or less

*        
尝试使用 "I:\some\python\Scripts\pip.exe" install NumPy也不行，提示：
I:\some>"I:\some\python\Scripts\pip.exe" install NumPy
Fatal error in launcher: Unable to create process using '"D:\some\python\python.exe"  "I:\some\python\Scripts\pip.exe" install NumPy': ???????????

*        
电脑里是装了Python 3.10.11的

**Comment by flutydeer** [comment]
那你自己拉代码下来配一下环境吧，整合包出这种问题我也不好排查，实在不行可以用 OpenUTAU

**Comment by NaughtDZ** [comment]
> 那你自己拉代码下来配一下环境吧，整合包出这种问题我也不好排查，实在不行可以用 OpenUTAU

不太行，我也没改任何文件，路径也没有中文啊

(venv) I:\some>webui.py --work_dir="dpcda"
Traceback (most recent call last):
  File "I:\some\webui.py", line 8, in <module>
    import gradio as gr
  File "I:\some\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "I:\some\venv\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "I:\some\venv\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "I:\some\venv\lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "I:\some\venv\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in <module>
    class MultimodalTextbox(FormComponent):
  File "I:\some\venv\lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "I:\some\venv\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
  File "C:\Program Files\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

**Comment by yqzhishen** [comment]
gradio 是不是太旧了，升级一下

`pip install -U gradio`

**Comment by NaughtDZ** [comment]
> gradio 是不是太旧了，升级一下
> 
> ```shell
> pip install -U gradio
> ```

不太行，安装时所有依赖均显示“Requirement already satisfied”
装完了再运行依旧GBK错误
